### ISSUE TITLE
Add a section with limitations

### ISSUE THREAD

**Issue by zehortigoza** [intel-aero/intel-aero-docs#5]
- AeroFC exposed I2Cs do not support I2C stretching

**Comment by anitha-suresh** [comment]
Currently it is @ https://github.com/intel-aero/meta-intel-aero/wiki/Known-Limitations-&-Work-Arounds

**Comment by zehortigoza** [comment]
Most of the itens in this page is already fixed in recent releases.

**Comment by anitha-suresh** [comment]
@zehortigoza right, we will have to check what still persists and then take applicable ones maybe

**Comment by anitha-suresh** [comment]
@zehortigoza , Understood that the ones mentioned in the wiki above are fixed :)

**Comment by anselmolsm** [comment]
On the other had, we'll have to list known issues of previous releases, we can't assume everybody is always running the latest release.
